# Generated by Django 4.2.2 on 2023-06-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctioncategory_name_listing_category_listing_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='seller',
        ),
    ]
