# Generated by Django 4.2.2 on 2023-06-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctioncategory_name_alter_listing_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='seller',
            new_name='seller_id',
        ),
    ]
