# Generated by Django 4.2.2 on 2023-06-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_start_price_alter_bid_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
