# Generated by Django 4.2.2 on 2023-06-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='have_bid',
            field=models.BooleanField(default=False),
        ),
    ]
