# Generated by Django 4.2.2 on 2023-07-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_like_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
